apiVersion: v1
kind: Service
metadata:
  name: cubestore-router
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cubestoreRouter.service.type }}
  ports:
    - port: {{ .Values.cubestoreRouter.service.service_port }}
      targetPort: {{ .Values.cubestoreRouter.service.port }}
      protocol: TCP
      name: http
    - port: 3030
      targetPort: 3030
      protocol: TCP
      name: http2
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql   
  selector:
    cubejsApp: cubestoreRouter
