apiVersion: v1
kind: Service
metadata:
  name: cube-refresh-worker
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cubeRefreshWorker.service.type }}
  ports:
    - port: {{ .Values.cubeRefreshWorker.service.service_port }}
      targetPort: {{ .Values.cubeRefreshWorker.service.port }}
      protocol: TCP
      name: http
  selector:
    cubejsApp: cubeRefreshWorker
