apiVersion: v1
data:
  {{- range $key, $val := .Values.cubestoreRouter.env.var }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}

kind: "ConfigMap"
metadata:
  name: {{ .Values.cubestoreRouter.configmap.name }}
  namespace: {{ .Values.namespace }}